#!/usr/bin/env bash


split_f () {
    flac_file=$(echo *.flac)
    shnsplit -f  *.cue -t %n-%t -o flac *.flac && rm "$flac_file";

    return;
}

for album in ./*
do
    cd "$album" && split_f && cd ../
done
